trigger:
- 'main'

variables:
  variables:
  buildConfiguration: 'Release'
  leaderboardRepository: 'leaderboard'
  webRepository: 'web'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'secret'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'

    steps:
    - task: Docker@2
      displayName: 'Build and push the image to container registry'
      inputs:
        containerRegistry: 'acrdevopsmasaki.azurecr.io'
        repository: '$(webRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: '$(tag)'

    - task: Docker@2
      displayName: 'Build and push the leaderboard image to container registry'
      inputs:
        containerRegistry: 'acrdevopsmasaki.azurecr.io'
        repository: '$(leaderboardRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.LeaderboardContainer/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: '$(tag)'
    
    - publish: '$(Build.SourcesDirectory)/manifests'
      artifact: manifests

- stage: 'Deploy'
  displayName: 'Deploy the containers'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: 'dev'
    variables:
    - group: 'Azure ENV'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: manifests

          - task: KubernetesManifest@1
            displayName: Create imagePullSecret
            inputs:
                action: createSecret
                connectionType: azureResourceManager
                secretName: $(imagePullSecret)
                dockerRegistryEndpoint: 'acrdevopsmasaki.azurecr.io'
                azureSubscriptionConnection: 'MSDN Platforms Subscription'
                azureResourceGroup: 'tailspin-space-game-rg'
                kubernetesCluster: 'tailspinspacegame-5455'
                namespace: 'dev'

          - task: KubernetesManifest@1
            displayName: Deploy to Kubernetes cluster
            inputs:
                action: deploy
                connectionType: azureResourceManager
                azureSubscriptionConnection: 'MSDN Platforms Subscription'
                azureResourceGroup: 'tailspin-space-game-rg'
                kubernetesCluster: 'tailspinspacegame-5455'
                namespace: 'dev'
                manifests: |
                    $(Pipeline.Workspace)/manifests/deployment.yml
                    $(Pipeline.Workspace)/manifests/service.yml
                imagePullSecrets: |
                    $(imagePullSecret)
                containers: |
                    $(RegistryName)/$(webRepository):$(tag)
                    $(RegistryName)/$(leaderboardRepository):$(tag)